-- 1.
SELECT STUDENT_NAME "학생 이름" , STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY "학생 이름" ASC;

-- 2.
SELECT STUDENT_NAME , STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3.
SELECT STUDENT_NAME 학생이름 , STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A'
AND (STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%')
ORDER BY "학생이름" ASC;

-- 4.
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR P
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과';

-- 5.
SELECT STUDENT_NO , TO_CHAR(POINT ,9.99)
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = '200402'
ORDER BY POINT DESC , STUDENT_NO ASC;

-- 6.
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

-- 7. ?
SELECT CLASS_NAME ,
(SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE TB_CLASS.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO)
FROM TB_CLASS
ORDER BY 1;

-- 8.
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

-- 9.
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_PROFESSOR TP
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE '인문사회' = (SELECT CATEGORY FROM TB_DEPARTMENT TD WHERE TD.DEPARTMENT_NO = TP.DEPARTMENT_NO);
    
-- 10. 미해결
SELECT
    STUDENT_NO "학번",
    STUDENT_NAME "학생이름",
    ROUND(AVG(POINT),1) "전체평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO , STUDENT_NAME;

-- 11.
SELECT DEPARTMENT_NAME , STUDENT_NAME , PROFESSOR_NAME
FROM TB_DEPARTMENT D, TB_STUDENT S , TB_PROFESSOR P
WHERE (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
AND (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
AND STUDENT_NO = 'A313047';

-- 11 풀이
SELECT
    DEPARTMENT_NAME 학과이름,
    STUDENT_NAME 학생이름,
    PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE STUDENT_NO = 'A313047';

-- 12.
SELECT STUDENT_NAME , TERM_NO
FROM TB_STUDENT S , TB_GRADE G , TB_CLASS C
WHERE (S.STUDENT_NO = G.STUDENT_NO)
AND (C.CLASS_NO = G.CLASS_NO) 
AND CLASS_NAME = '인간관계론'
AND SUBSTR(TERM_NO,1,4) = '2007';

-- 12 풀이
SELECT
    STUDENT_NAME,
    TERM_NO TERM_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론'
AND SUBSTR(TERM_NO,1,4) = '2007';
    
-- 13. 미해결
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NAME IS NULL;

-- 13 풀이
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

-- 14.
SELECT S.STUDENT_NAME 학생이름, NVL(P.PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE;

-- 14 풀이
SELECT
    STUDENT_NAME 학생이름,
    NVL(PROFESSOR_NAME , '지도교수 미지정') 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE DEPARTMENT_NAME = '서반아어학과';

-- 15.
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME , AVG(POINT)
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN TB_GRADE G USING (STUDENT_NO)
WHERE ABSENCE_YN <> 'Y'
GROUP BY STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
HAVING AVG(POINT)>= 4.0;

-- 15 풀이
SELECT
    STUDENT_NO ,
    STUDENT_NAME
    DEPARTMENT_NAME,
    AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN != 'Y'
GROUP BY STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
HAVING AVG(POINT)>=4.0;

-- 16.
SELECT CLASS_NO , CLASS_NAME , AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
WHERE '환경조경학과' = (SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE TB_CLASS.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO)
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO , CLASS_NAME;

-- 16 풀이
SELECT
    CLASS_NO,
    CLASS_NAME,
    AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO , CLASS_NAME;

-- 17.
SELECT STUDENT_NAME , STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

-- 17 풀이
SELECT
    STUDENT_NAME,
    STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME='최경희');
-- 동명이인 있는경우? 값이 두개가 나온다면?

-- 18. 미해결
SELECT *
FROM TB_STUDENT S
JOIN (SELECT STUDENT_NO , AVG(POINT) AS 평균 FROM TB_GRADE GROUP BY STUDENT_NO) USING(STUDENT_NO)
WHERE '국어국문학과' = (SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT D WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO);

-- 18 풀이 1
SELECT
    STUDENT_NO,
    STUDENT_NAME,
    AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO , STUDENT_NAME
HAVING AVG(POINT) = (
SELECT
    MAX(AVG(POINT))
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO , STUDENT_NAME
);

-- 18 풀이 2
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT
    STUDENT_NO,
    STUDENT_NAME,
    AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO , STUDENT_NAME
ORDER BY 3 DESC)
WHERE ROWNUM = 1;

-- 19.
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(학생평균),1) AS "전공평점"
FROM TB_DEPARTMENT
JOIN (SELECT *
FROM TB_STUDENT
JOIN (SELECT STUDENT_NO , AVG(POINT) AS "학생평균"
FROM TB_GRADE
GROUP BY STUDENT_NO) USING (STUDENT_NO)
) USING (DEPARTMENT_NO)
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;

-- 19 풀이
SELECT
    DEPARTMENT_NAME "계열 학과명",
    ROUND(AVG(POINT),1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (CLASS_NO)
WHERE CLASS_TYPE LIKE '%전공%'
AND CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;