DROP TABLE TB_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE TB_CLASS_TYPE;
-- 1.
CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2.
CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT TC_PK_NAME PRIMARY KEY (NAME);

-- 4.
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME CONSTRAINT TC_NN_NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

-- 6.
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CATEGORY_NO
RENAME COLUMN NAME TO CATEGORY_NAME;

-- 7.
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT TC_PK_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C008544 TO PR_CLASS_TYPE_NO;

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- 10.
CREATE TABLE VW_학생일반정보
AS (SELECT STUDENT_NO , STUDENT_NAME , STUDENT_ADDRESS  FROM TB_STUDENT);

DROP TABLE VW_학생일반정보;

-- 11.
