CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,               
  USER_ID VARCHAR2(30) NOT NULL UNIQUE,   
  USER_PWD VARCHAR2(100) NOT NULL,  
  USER_NAME VARCHAR2(15) NOT NULL,    
  EMAIL VARCHAR2(100),        
  BIRTHDAY VARCHAR2(6),
  GENDER VARCHAR2(1) CHECK (GENDER IN('M', 'F')),    
  PHONE VARCHAR2(13),            
  ADDRESS VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_UNO NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', 'admin@kh.or.kr', '800918', 'F', '010-1111-2222', '서울시 강남구 역삼동', SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'user01@kh.or.kr', '900213', 'M', '010-3333-4444', '서울시 마포구 공덕동', SYSDATE, SYSDATE, DEFAULT);

-- member계정으로 실행

COMMIT;