-- 1.
SELECT
    STUDENT_NO "학번",
    STUDENT_NAME "이름",
    ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

-- 2.
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

-- 3.
SELECT
    PROFESSOR_NAME "교수이름",
    EXTRACT(YEAR FROM SYSDATE) - (19|| SUBSTR(PROFESSOR_SSN,1,2)) AS "나이"
    -- ROUND((SYSDATE - TO_DATE((SUBSTR(PROFESSOR_SSN,1,6)),'YYMMDD') + 100*365)/365) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY "나이" ASC;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2) AS "이름"
FROM TB_PROFESSOR;

-- 5.
SELECT
    STUDENT_NO,
    STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT (YEAR FROM ENTRANCE_DATE) - EXTRACT (YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6) , 'RRMMDD')) > 19; 

-- 6.
SELECT TO_CHAR(TO_DATE(20201225),'DY')
FROM DUAL;

-- 7.
-- 2099.10.11
-- 2049.10.11
-- 1999.10.11
-- 2049.10.11

-- 8.
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) <> 'A';
-- WHERE STUDENT_NO NOT LIKE 'A%';

-- 9.
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';
-- GROUP BY STUDENT_NO ;

-- 10.
SELECT
    DEPARTMENT_NO AS "학과번호",
    COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
-- WHERE COACH_PROFESSOR_NO IS NULL
GROUP BY COACH_PROFESSOR_NO
HAVING COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT
    SUBSTR(TERM_NO,1,4) AS "년도",
    ROUND(AVG(POINT),1) AS "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

-- 13.
SELECT
    DEPARTMENT_NO AS "학과코드명",
    COUNT(CASE WHEN ABSENCE_YN = 'Y' THEN 1 END) AS "휴학생 수"
    -- COUNT(DECODE(ABSENCE_YN,'Y',1))
FROM TB_STUDENT
-- WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 14.
SELECT STUDENT_NAME AS "동일이름",COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY STUDENT_NAME;

-- 15.
SELECT
    SUBSTR(TERM_NO,1,4) AS "년도",
    SUBSTR(TERM_NO,5,2) AS "학기", 
    ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4) , SUBSTR(TERM_NO,5,2))
ORDER BY "년도" ASC;
/*
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2)
UNION ALL 
SELECT SUBSTR(TERM_NO,1,4) 년도,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
UNION ALL
SELECT NULL,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
ORDER BY 년도, 2
;
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 1;
*/